name: PR Validation
on: push

jobs:
  scalaFmt:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache SBT & ivy cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/plugins.sbt') }}-${{ hashFiles('**/build.properties') }}
      - name: Check formatting
        run: sbt scalafmtCheckAll

  test:
    name: Compile and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache SBT & ivy cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/plugins.sbt') }}-${{ hashFiles('**/build.properties') }}
      - name: Compile and test
        run: sbt -batch "; docs/mdoc; +test; +doc; version"
